# This is a basic workflow to help you get started with Actions

name: CI-CD
env:
  node-version: 14.x
  aws-region: eu-central-1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow contains 3 phases: build, deploy-test, deploy-prod
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: build
        run: sh ./build.sh

  compare-test:
    needs: [build] # when build succeeded
    env:
      NODE_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: build
        run: sh ./build.sh

      - name: compare incoming and target CloudFormation stacks
        run: cdk diff
        working-directory: ./snake-iac

  deploy-test:
    needs: [compare-test] # when differences are shown
    environment: test
    env:
      NODE_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: build
        run: sh ./build.sh

      - name: deploy updated CloudFormation stack
        run: cdk deploy --ci --require-approval never
        working-directory: ./snake-iac

  compare-prod:
    needs: [deploy-test] # after test deployment
    env:
      NODE_ENV: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: build
        run: sh ./build.sh

      - name: compare incoming and target CloudFormation stacks
        run: cdk diff
        working-directory: ./snake-iac

  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' }} # main branch only
    needs: [compare-prod] # when differences are shown
    environment: prod
    env:
      NODE_ENV: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: build
        run: sh ./build.sh

      - name: deploy updated CloudFormation stack
        run: cdk deploy --ci --require-approval never
        working-directory: ./snake-iac
